Minor: applying shfmt: format existing scripts with indent 4

diff --git a/scripts/bash/bash_template_depend_on_bash_source b/scripts/bash/bash_template_depend_on_bash_source
--- a/scripts/bash/bash_template_depend_on_bash_source
+++ b/scripts/bash/bash_template_depend_on_bash_source
@@ -5,20 +5,20 @@
 
 # Enable xtrace if the DEBUG environment variable is set
 if [[ ${DEBUG-} =~ ^1|yes|true$ ]]; then
-    set -o xtrace       # Trace the execution of the script (debug)
+    set -o xtrace # Trace the execution of the script (debug)
 fi
 
 # Only enable these shell behaviours if we're not being sourced
 # Approach via: https://stackoverflow.com/a/28776166/8787985
 if ! (return 0 2> /dev/null); then
     # A better class of script...
-    set -o errexit      # Exit on most errors (see the manual)
-    set -o nounset      # Disallow expansion of unset variables
-    set -o pipefail     # Use last non-zero exit code in a pipeline
+    set -o errexit  # Exit on most errors (see the manual)
+    set -o nounset  # Disallow expansion of unset variables
+    set -o pipefail # Use last non-zero exit code in a pipeline
 fi
 
 # Enable errtrace or the error trap handler will not work as expected
-set -o errtrace         # Ensure the error trap handler is inherited
+set -o errtrace # Ensure the error trap handler is inherited
 
 # DESC: Usage help
 # ARGS: None
