Minor: vscode script for remote: use bash version instead of zsh version

diff --git a/linux/ubuntu/remote_vscode/code b/linux/ubuntu/remote_vscode/code
--- a/linux/ubuntu/remote_vscode/code
+++ b/linux/ubuntu/remote_vscode/code
@@ -1,19 +1,28 @@
-#!/usr/bin/env zsh
+#!/bin/bash
 
-local script=$(echo ~/.vscode-server/bin/*/bin/remote-cli/code(*oc[1]N))
-if [[ -z ${script} ]]
-then
-    echo "VSCode remote script not found"
-    exit 1
-fi
+max_retry=3
 
-local socket=$(echo /run/user/$UID/vscode-ipc-*.sock(=oc[1]N))
-if [[ -z ${socket} ]]
-then
-    echo "VSCode IPC socket not found"
-    exit 1
-fi
+for i in $(seq 1 $max_retry)
+do
+    recent_folder=$(ls ~/.vscode-server/bin/ -t | head -n$i)
+    script=$(echo ~/.vscode-server/bin/$recent_folder/bin/remote-cli/code)
+    if [[ -z ${script} ]]
+    then
+        echo "VSCode remote script not found"
+        exit 1
+    fi
+    socket=$(ls /run/user/$UID/vscode-ipc-* -t | head -n$i)
+    if [[ -z ${socket} ]]
+    then
+        echo "VSCode IPC socket not found"
+        exit 1
+    fi
+    export VSCODE_IPC_HOOK_CLI=${socket}
+    ${script} $@
+    if [ "$?" -eq "0" ]; then
+        exit 0
+    fi
+done
 
-export VSCODE_IPC_HOOK_CLI=${socket}
-# echo $script $@
-${script} $@
+echo "Failed to find valid VS Code window"
+
